// Generated from docs/race-gpx-manifest/races.json — do not hand-edit rows, regenerate instead.
export interface FamousRace {
  id: string
  row: number
  name: string
  organizer: string
  location: string
  continent: string
  distance: string
  officialDPlus: string
  category: string
  dateLabel: string
  gpxSource: string
  login: string
  terms: string
  groupLabel: string
}

export const FAMOUS_RACES: FamousRace[] = [
  {
    id: "sierre-zinal-1",
    row: 1,
    name: "Sierre-Zinal",
    organizer: "Assoc. Sierre-Zinal (Golden Trail World Series)",
    location: "Switzerland – Valais",
    continent: "Europe",
    distance: "31.3 km (records: Jornet 2:25:35, Mathys 2:46:03)",
    officialDPlus: "2190 m (1,100 m descent)",
    category: "20K/Sky",
    dateLabel: "Sat 8 Aug 2026 (53rd ed.)",
    gpxSource: "https://www.sierre-zinal.com/fr/coordonnees-coureur-751.html (official, send-to-device); UNOFFICIAL tracedetrail.fr/fr/trace/25180",
    login: "Official: send-to-device; TdT: yes",
    terms: "Cookie consent only",
    groupLabel: "20K / Sky / VK",
  },
  {
    id: "zegama-aizkorri-maratoia-2",
    row: 2,
    name: "Zegama-Aizkorri (Maratoia)",
    organizer: "Antxintxika K.E. (Golden Trail World Series)",
    location: "Spain – Basque Country",
    continent: "Europe",
    distance: "42.195 km",
    officialDPlus: "2736 m",
    category: "50K borderline",
    dateLabel: "May",
    gpxSource: "https://www.zegama-aizkorri.com/en/mendi-maratoia-zegama/tracks (official \"Download GPX\")",
    login: "No",
    terms: "Course crosses Aizkorri massif",
    groupLabel: "20K / Sky / VK",
  },
  {
    id: "zegama-aizkorri-vk-3",
    row: 3,
    name: "Zegama-Aizkorri VK",
    organizer: "Antxintxika K.E.",
    location: "Spain – Basque Country",
    continent: "Europe",
    distance: "3.2 km",
    officialDPlus: "976 m",
    category: "VK",
    dateLabel: "May",
    gpxSource: "UNOFFICIAL tracedetrail.fr/en/trace/245830",
    login: "Yes (TdT)",
    terms: "—",
    groupLabel: "20K / Sky / VK",
  },
  {
    id: "matterhorn-ultraks-sky-4",
    row: 4,
    name: "Matterhorn Ultraks (Sky)",
    organizer: "Ultraks",
    location: "Switzerland – Zermatt",
    continent: "Europe",
    distance: "~30 km",
    officialDPlus: "~3000 m",
    category: "20K/Sky",
    dateLabel: "Aug",
    gpxSource: "Organiser ultraks.com (verify \"parcours\"); UNOFFICIAL Wikiloc",
    login: "verify",
    terms: "Alpine private land",
    groupLabel: "20K / Sky / VK",
  },
  {
    id: "transvulcania-vk-5",
    row: 5,
    name: "Transvulcania VK",
    organizer: "Transvulcania",
    location: "Spain – La Palma",
    continent: "Europe",
    distance: "7.26 km",
    officialDPlus: "1203 m",
    category: "VK",
    dateLabel: "May",
    gpxSource: "Organiser transvulcania.com (GPX not confirmed); UNOFFICIAL Wikiloc",
    login: "verify",
    terms: "GR-131 route",
    groupLabel: "20K / Sky / VK",
  },
  {
    id: "trail-almere-6",
    row: 6,
    name: "Trail Almere",
    organizer: "local organizer",
    location: "Netherlands – Flevoland",
    continent: "Europe",
    distance: "~10–25 km",
    officialDPlus: "minimal (polder)",
    category: "20K",
    dateLabel: "varies",
    gpxSource: "Not found (organiser); UNOFFICIAL community GPX",
    login: "—",
    terms: "Flat polder course",
    groupLabel: "20K / Sky / VK",
  },
  {
    id: "occ-7",
    row: 7,
    name: "OCC",
    organizer: "UTMB World Series Finals",
    location: "France/Switzerland – Chamonix",
    continent: "Europe",
    distance: "60 km",
    officialDPlus: "3500 m",
    category: "50K",
    dateLabel: "Aug (24–30 Aug 2026)",
    gpxSource: "https://montblanc.utmb.world/races/OCC",
    login: "No",
    terms: "Crosses private property (UTMB terms)",
    groupLabel: "20K / Sky / VK",
  },
  {
    id: "mcc-8",
    row: 8,
    name: "MCC",
    organizer: "UTMB World Series Finals",
    location: "France – Chamonix",
    continent: "Europe",
    distance: "40 km",
    officialDPlus: "2300 m",
    category: "20K",
    dateLabel: "Aug",
    gpxSource: "https://montblanc.utmb.world/races (MCC page)",
    login: "No",
    terms: "UTMB terms",
    groupLabel: "20K / Sky / VK",
  },
  {
    id: "etc-experience-trail-courmayeur-9",
    row: 9,
    name: "ETC (Experience Trail Courmayeur)",
    organizer: "UTMB World Series Finals",
    location: "Italy – Courmayeur",
    continent: "Europe",
    distance: "15 km",
    officialDPlus: "1300 m",
    category: "20K",
    dateLabel: "Aug",
    gpxSource: "https://montblanc.utmb.world/races (ETC page)",
    login: "No",
    terms: "UTMB terms",
    groupLabel: "20K / Sky / VK",
  },
  {
    id: "vielha-10k-val-d-aran-10",
    row: 10,
    name: "Vielha 10K (Val d'Aran)",
    organizer: "HOKA Val d'Aran by UTMB",
    location: "Spain – Val d'Aran",
    continent: "Europe",
    distance: "10 km",
    officialDPlus: "—",
    category: "20K",
    dateLabel: "Jul",
    gpxSource: "https://valdaran.utmb.world/race/tracks",
    login: "No",
    terms: "Private property",
    groupLabel: "20K / Sky / VK",
  },
  {
    id: "restonica-giru-di-tumbone-11",
    row: 11,
    name: "Restonica – Giru di Tumbone",
    organizer: "Restonica Trail by UTMB",
    location: "France – Corsica, Corte",
    continent: "Europe",
    distance: "17 km",
    officialDPlus: "665 m",
    category: "20K",
    dateLabel: "Jul (9–11 Jul 2026)",
    gpxSource: "https://www.restonicatrail.fr/maps-and-profiles-2024/ (Openrunner/TdT)",
    login: "Yes",
    terms: "Tavignanu biological reserve",
    groupLabel: "20K / Sky / VK",
  },
  {
    id: "eryri-25k-ex-uts-12",
    row: 12,
    name: "Eryri 25K (ex-UTS)",
    organizer: "Ultra-Trail Snowdonia by UTMB",
    location: "Wales – Eryri/Snowdonia",
    continent: "Europe",
    distance: "25 km",
    officialDPlus: "1400 m",
    category: "20K",
    dateLabel: "May",
    gpxSource: "https://snowdonia.utmb.world/races",
    login: "No",
    terms: "National park",
    groupLabel: "20K / Sky / VK",
  },
  {
    id: "verbier-x-plore-13",
    row: 13,
    name: "Verbier X-Plore",
    organizer: "Trail Verbier St-Bernard by UTMB",
    location: "Switzerland – Verbier",
    continent: "Europe",
    distance: "28 km",
    officialDPlus: "1700 m",
    category: "20K",
    dateLabel: "Jul",
    gpxSource: "https://verbier.utmb.world/races",
    login: "No",
    terms: "UTMB terms",
    groupLabel: "20K / Sky / VK",
  },
  {
    id: "julian-alps-25k-14",
    row: 14,
    name: "Julian Alps 25K",
    organizer: "Julian Alps Trail Run by UTMB",
    location: "Slovenia – Kranjska Gora",
    continent: "Europe",
    distance: "25 km",
    officialDPlus: "1028 m",
    category: "20K",
    dateLabel: "Sep (17–20 Sep 2026)",
    gpxSource: "https://julianalps.utmb.world/races (Routes tab, final files end Aug)",
    login: "No",
    terms: "Follow marked SAA paths; use pasture gates",
    groupLabel: "20K / Sky / VK",
  },
  {
    id: "chianti-20k-15",
    row: 15,
    name: "Chianti 20K",
    organizer: "Chianti Ultra Trail by UTMB",
    location: "Italy – Tuscany",
    continent: "Europe",
    distance: "~21 km",
    officialDPlus: "~700 m",
    category: "20K",
    dateLabel: "Mar/Apr",
    gpxSource: "https://chianti.utmb.world/race/tracks (verify)",
    login: "No",
    terms: "UTMB terms",
    groupLabel: "20K / Sky / VK",
  },
  {
    id: "bear-trail-17k-16",
    row: 16,
    name: "Bear Trail 17K",
    organizer: "Bearsports",
    location: "Belgium – Voeren",
    continent: "Europe",
    distance: "17 km",
    officialDPlus: "~400 m",
    category: "20K",
    dateLabel: "Sat 24 Oct 2026",
    gpxSource: "Organiser bearsports.nl/bear-trail (GPX posted days before); UNOFFICIAL tracedetrail.fr/en/map/343",
    login: "—",
    terms: "\"GPX-bestanden worden enkele dagen voor het event online gezet\"",
    groupLabel: "20K / Sky / VK",
  },
  {
    id: "amerongse-berg-trail-17",
    row: 17,
    name: "Amerongse Berg trail",
    organizer: "local (Utrechtse Heuvelrug)",
    location: "Netherlands – Utrecht",
    continent: "Europe",
    distance: "~15–25 km",
    officialDPlus: "modest",
    category: "20K",
    dateLabel: "varies",
    gpxSource: "Not found (organised event); UNOFFICIAL community GPX",
    login: "—",
    terms: "—",
    groupLabel: "20K / Sky / VK",
  },
  {
    id: "sallandse-heuvelrug-trail-18",
    row: 18,
    name: "Sallandse Heuvelrug trail",
    organizer: "local",
    location: "Netherlands – Overijssel",
    continent: "Europe",
    distance: "~20–30 km",
    officialDPlus: "modest",
    category: "20K",
    dateLabel: "varies",
    gpxSource: "Not found; UNOFFICIAL community GPX",
    login: "—",
    terms: "National park",
    groupLabel: "20K / Sky / VK",
  },
  {
    id: "kullamannen-20k-19",
    row: 19,
    name: "Kullamannen 20K",
    organizer: "Kullamannen by UTMB",
    location: "Sweden – Skåne",
    continent: "Europe",
    distance: "~20 km",
    officialDPlus: "~600 m",
    category: "20K",
    dateLabel: "Oct/Nov",
    gpxSource: "https://kullamannen.utmb.world/race/tracks (verify)",
    login: "No",
    terms: "UTMB terms",
    groupLabel: "20K / Sky / VK",
  },
  {
    id: "sezoenstrail-short-20",
    row: 20,
    name: "Sezoenstrail (short)",
    organizer: "Sezoenstrail",
    location: "Belgium – Limburg",
    continent: "Europe",
    distance: "~21 km",
    officialDPlus: "modest",
    category: "20K",
    dateLabel: "Mar",
    gpxSource: "Organiser (verify parcours); UNOFFICIAL betrail.run",
    login: "verify",
    terms: "—",
    groupLabel: "20K / Sky / VK",
  },
  {
    id: "ccc-21",
    row: 21,
    name: "CCC",
    organizer: "UTMB World Series Finals",
    location: "Italy/Switz/France – Courmayeur→Chamonix",
    continent: "Europe",
    distance: "101 km (start Courmayeur Fri 09:00, cutoff 26:30)",
    officialDPlus: "~6050 m",
    category: "100K",
    dateLabel: "Aug",
    gpxSource: "https://montblanc.utmb.world/races/CCC",
    login: "No",
    terms: "Private property",
    groupLabel: "50K",
  },
  {
    id: "cortina-trail-22",
    row: 22,
    name: "Cortina Trail",
    organizer: "Lavaredo by UTMB",
    location: "Italy – Cortina d'Ampezzo",
    continent: "Europe",
    distance: "48 km",
    officialDPlus: "2630 m",
    category: "50K",
    dateLabel: "Jun",
    gpxSource: "https://lavaredo.utmb.world/races (Cortina page); UNOFFICIAL tracedetrail.fr/en/trace/48923",
    login: "No",
    terms: "Dolomites",
    groupLabel: "50K",
  },
  {
    id: "transvulcania-ultramarathon-23",
    row: 23,
    name: "Transvulcania Ultramarathon",
    organizer: "Transvulcania",
    location: "Spain – La Palma",
    continent: "Europe",
    distance: "73.06 km",
    officialDPlus: "4350 m",
    category: "100K",
    dateLabel: "Sat 9 May 2026",
    gpxSource: "Organiser transvulcania.com/en/modalities (GPX not confirmed); UNOFFICIAL Wikiloc 20829195",
    login: "verify",
    terms: "GR-131 \"Ruta del Bastón\"",
    groupLabel: "50K",
  },
  {
    id: "transgrancanaria-marathon-46k-24",
    row: 24,
    name: "Transgrancanaria Marathon 46K",
    organizer: "Arista Eventos",
    location: "Spain – Gran Canaria",
    continent: "Europe",
    distance: "45.9 km",
    officialDPlus: "1589 m",
    category: "50K",
    dateLabel: "Feb (26 Feb 2027)",
    gpxSource: "https://transgrancanaria.net/en/marathon-46km/ (right-click download link)",
    login: "No",
    terms: "\"Google Earth may change distance/elev; GPX most reliable\"",
    groupLabel: "50K",
  },
  {
    id: "miut-marathon-42-25",
    row: 25,
    name: "MIUT Marathon 42",
    organizer: "Madeira Island Ultra Trail",
    location: "Portugal – Madeira",
    continent: "Europe",
    distance: "40 km",
    officialDPlus: "1450 m",
    category: "50K",
    dateLabel: "24–25 Apr 2027",
    gpxSource: "Organiser miutmadeira.com; UNOFFICIAL tracedetrail.fr",
    login: "verify/Yes",
    terms: "Levada/laurel forest",
    groupLabel: "50K",
  },
  {
    id: "miut-discover-56-26",
    row: 26,
    name: "MIUT Discover 56",
    organizer: "Madeira Island Ultra Trail",
    location: "Portugal – Madeira",
    continent: "Europe",
    distance: "56 km",
    officialDPlus: "2810 m",
    category: "50K",
    dateLabel: "Apr",
    gpxSource: "Organiser miutmadeira.com; UNOFFICIAL tracedetrail.fr",
    login: "verify",
    terms: "—",
    groupLabel: "50K",
  },
  {
    id: "verbier-marathon-27",
    row: 27,
    name: "Verbier Marathon",
    organizer: "Trail Verbier St-Bernard by UTMB",
    location: "Switzerland – Verbier",
    continent: "Europe",
    distance: "43 km",
    officialDPlus: "3000 m",
    category: "50K",
    dateLabel: "Jul",
    gpxSource: "https://verbier.utmb.world/races",
    login: "No",
    terms: "UTMB terms",
    groupLabel: "50K",
  },
  {
    id: "eiger-e51-28",
    row: 28,
    name: "Eiger E51",
    organizer: "Eiger Ultra Trail by UTMB",
    location: "Switzerland – Grindelwald",
    continent: "Europe",
    distance: "51 km",
    officialDPlus: "~3100 m",
    category: "50K",
    dateLabel: "Jul (18 Jul 2026)",
    gpxSource: "https://eiger.utmb.world/races",
    login: "No",
    terms: "Alpine",
    groupLabel: "50K",
  },
  {
    id: "restonica-trail-56-69k-29",
    row: 29,
    name: "Restonica Trail (56–69K)",
    organizer: "Restonica Trail by UTMB",
    location: "France – Corsica, Corte",
    continent: "Europe",
    distance: "56–69 km",
    officialDPlus: "2960–3900 m",
    category: "50K/100K",
    dateLabel: "Jul",
    gpxSource: "https://www.restonicatrail.fr/maps-and-profiles-2024/",
    login: "Yes",
    terms: "Regional Natural Park; GPX = 1 pt/10 m",
    groupLabel: "50K",
  },
  {
    id: "trail-100-andorra-50k-30",
    row: 30,
    name: "Trail 100 Andorra – 50K",
    organizer: "Trail 100 Andorra by UTMB",
    location: "Andorra",
    continent: "Europe",
    distance: "~55 km",
    officialDPlus: "~3300 m",
    category: "50K",
    dateLabel: "Jul",
    gpxSource: "https://andorra.utmb.world/races (verify)",
    login: "No",
    terms: "UTMB terms",
    groupLabel: "50K",
  },
  {
    id: "zugspitz-basetrail-supertrail-31",
    row: 31,
    name: "Zugspitz Basetrail/Supertrail",
    organizer: "Zugspitz Ultratrail by UTMB",
    location: "Germany – Garmisch",
    continent: "Europe",
    distance: "44–68 km",
    officialDPlus: "~2000–3000 m",
    category: "50K/100K",
    dateLabel: "18–20 Jun 2026",
    gpxSource: "https://zugspitz.utmb.world/races",
    login: "No",
    terms: "Weather shortening possible",
    groupLabel: "50K",
  },
  {
    id: "eryri-uts-50k-32",
    row: 32,
    name: "Eryri/UTS 50K",
    organizer: "Ultra-Trail Snowdonia by UTMB",
    location: "Wales – Snowdonia",
    continent: "Europe",
    distance: "56 km",
    officialDPlus: "3400 m",
    category: "50K",
    dateLabel: "May",
    gpxSource: "https://snowdonia.utmb.world/races",
    login: "No",
    terms: "National park",
    groupLabel: "50K",
  },
  {
    id: "trail-du-mont-blanc-marathon-33",
    row: 33,
    name: "Trail du Mont-Blanc (Marathon)",
    organizer: "Trail du Mont-Blanc / Chamonix",
    location: "France – Chamonix",
    continent: "Europe",
    distance: "42 km",
    officialDPlus: "2540 m",
    category: "50K",
    dateLabel: "Jun/Jul",
    gpxSource: "Organiser montblancmarathon.net (verify parcours); UNOFFICIAL tracedetrail.fr",
    login: "verify",
    terms: "Alpine",
    groupLabel: "50K",
  },
  {
    id: "grand-raid-des-pyrenees-neouvielle-34",
    row: 34,
    name: "Grand Raid des Pyrénées – Néouvielle",
    organizer: "GRP",
    location: "France – Hautes-Pyrénées",
    continent: "Europe",
    distance: "40–43 km",
    officialDPlus: "2400 m",
    category: "50K",
    dateLabel: "Aug",
    gpxSource: "https://www.grandraidpyrenees.com/en/coursesgrp/ (emailed); UNOFFICIAL tracedetrail.fr event page",
    login: "verify",
    terms: "Col de Portet closures",
    groupLabel: "50K",
  },
  {
    id: "rennsteiglauf-supermarathon-35",
    row: 35,
    name: "Rennsteiglauf Supermarathon",
    organizer: "GutsMuths-Rennsteiglauf",
    location: "Germany – Thuringia",
    continent: "Europe",
    distance: "73.9 km",
    officialDPlus: "~1600 m",
    category: "100K borderline",
    dateLabel: "22 May 2027",
    gpxSource: "https://www.rennsteiglauf.de/en/race/courses/ (via Outdooractive)",
    login: "Outdooractive account",
    terms: "\"GPS tracks for personal use only, no redistribution\"",
    groupLabel: "50K",
  },
  {
    id: "squamish-50-36",
    row: 36,
    name: "Squamish 50",
    organizer: "Squamish 50 / Gary Robbins",
    location: "Canada – BC",
    continent: "N. America",
    distance: "50 mi/80 km",
    officialDPlus: "~3350 m",
    category: "100K",
    dateLabel: "Aug",
    gpxSource: "Organiser squamish50.com (verify); UNOFFICIAL community",
    login: "verify",
    terms: "—",
    groupLabel: "50K",
  },
  {
    id: "quebec-mega-trail-qmt-37",
    row: 37,
    name: "Quebec Mega Trail (QMT)",
    organizer: "Quebec Mega Trail",
    location: "Canada – Quebec",
    continent: "N. America",
    distance: "~50–100 km",
    officialDPlus: "varies",
    category: "50K/100K",
    dateLabel: "Jul",
    gpxSource: "quebecmegatrail.com no longer resolves (DNS failure, confirmed 2026-09-08); event may now run as Ultra-Trail Canada — UNOFFICIAL, unconfirmed lead ultratrailcanada.com",
    login: "verify",
    terms: "—",
    groupLabel: "50K",
  },
  {
    id: "black-canyon-ultras-60k-100k-38",
    row: 38,
    name: "Black Canyon Ultras 60K/100K",
    organizer: "Aravaipa Running",
    location: "USA – Arizona",
    continent: "N. America",
    distance: "60 km/100 km",
    officialDPlus: "~1200/1700 m",
    category: "50K/100K",
    dateLabel: "Feb",
    gpxSource: "Organiser aravaiparunning.com (verify)",
    login: "verify",
    terms: "—",
    groupLabel: "50K",
  },
  {
    id: "canyons-50k-39",
    row: 39,
    name: "Canyons 50K",
    organizer: "Canyons Endurance Runs by UTMB",
    location: "USA – California",
    continent: "N. America",
    distance: "50 km",
    officialDPlus: "~2000 m",
    category: "50K",
    dateLabel: "Apr",
    gpxSource: "https://canyons.utmb.world/races",
    login: "No",
    terms: "Western States Trail",
    groupLabel: "50K",
  },
  {
    id: "trail-menorca-cami-de-cavalls-40",
    row: 40,
    name: "Trail Menorca Camí de Cavalls",
    organizer: "Trail Menorca",
    location: "Spain – Menorca",
    continent: "Europe",
    distance: "~185 km (also 100/45)",
    officialDPlus: "~3000 m",
    category: "multi/100M",
    dateLabel: "May",
    gpxSource: "Organiser trailmenorca.com (verify); UNOFFICIAL Wikiloc",
    login: "verify",
    terms: "Camí de Cavalls GR-223",
    groupLabel: "50K",
  },
  {
    id: "matterhorn-ultraks-46k-41",
    row: 41,
    name: "Matterhorn Ultraks 46K",
    organizer: "Ultraks",
    location: "Switzerland – Zermatt",
    continent: "Europe",
    distance: "46 km",
    officialDPlus: "3600 m",
    category: "50K",
    dateLabel: "Aug",
    gpxSource: "Organiser ultraks.com (verify)",
    login: "verify",
    terms: "Alpine",
    groupLabel: "50K",
  },
  {
    id: "trail-des-cathares-42",
    row: 42,
    name: "Trail des Cathares",
    organizer: "organiser",
    location: "France – Aude/Pyrénées",
    continent: "Europe",
    distance: "~200 km stage (also shorter)",
    officialDPlus: "~10000 m",
    category: "multi",
    dateLabel: "Oct",
    gpxSource: "traildescathares.com no longer resolves (DNS failure, confirmed 2026-09-08); UNOFFICIAL, unconfirmed lead grandraid-cathares.fr — reportedly no official GPX is published (private-property sections); UNOFFICIAL tracedetrail.fr",
    login: "verify",
    terms: "Cathar castles route",
    groupLabel: "50K",
  },
  {
    id: "ecotrail-paris-45k-43",
    row: 43,
    name: "Ecotrail Paris 45K",
    organizer: "Ecotrail",
    location: "France – Paris/Versailles",
    continent: "Europe",
    distance: "45 km",
    officialDPlus: "~700 m",
    category: "50K",
    dateLabel: "Mar",
    gpxSource: "Organiser ecotrailparis.com (verify)",
    login: "verify",
    terms: "Peri-urban",
    groupLabel: "50K",
  },
  {
    id: "chianti-ultra-trail-50k-44",
    row: 44,
    name: "Chianti Ultra Trail 50K",
    organizer: "Chianti Ultra Trail by UTMB",
    location: "Italy – Tuscany",
    continent: "Europe",
    distance: "~50 km",
    officialDPlus: "~1800 m",
    category: "50K",
    dateLabel: "Mar/Apr",
    gpxSource: "https://chianti.utmb.world/race/tracks (verify)",
    login: "No",
    terms: "UTMB terms",
    groupLabel: "50K",
  },
  {
    id: "bear-trail-40k-60k-45",
    row: 45,
    name: "Bear Trail 40K/60K",
    organizer: "Bearsports",
    location: "Belgium – Voeren",
    continent: "Europe",
    distance: "40/60 km",
    officialDPlus: "~1000/1600 m",
    category: "50K/100K",
    dateLabel: "24 Oct 2026",
    gpxSource: "bearsports.nl/bear-trail (posted days before)",
    login: "—",
    terms: "Posted just before event",
    groupLabel: "50K",
  },
  {
    id: "lavaredo-ultra-trail-120k-46",
    row: 46,
    name: "Lavaredo Ultra Trail 120K",
    organizer: "La Sportiva Lavaredo by UTMB",
    location: "Italy – Cortina",
    continent: "Europe",
    distance: "120 km",
    officialDPlus: "5800 m",
    category: "100K",
    dateLabel: "Jun",
    gpxSource: "https://lavaredo.utmb.world/races; UNOFFICIAL tracedetrail.fr/en/trace/146923",
    login: "No",
    terms: "Dolomites UNESCO",
    groupLabel: "100K",
  },
  {
    id: "ccc-47",
    row: 47,
    name: "CCC",
    organizer: "UTMB World Series Finals",
    location: "Italy→France",
    continent: "Europe",
    distance: "101 km",
    officialDPlus: "~6050 m",
    category: "100K",
    dateLabel: "Aug",
    gpxSource: "https://montblanc.utmb.world/races/CCC",
    login: "No",
    terms: "Private property",
    groupLabel: "100K",
  },
  {
    id: "tds-48",
    row: 48,
    name: "TDS",
    organizer: "UTMB World Series Finals",
    location: "France/Italy – Chamonix",
    continent: "Europe",
    distance: "145 km (start Courmayeur Mon 23:50, cutoff 44:55)",
    officialDPlus: "~9500 m",
    category: "100M",
    dateLabel: "Aug",
    gpxSource: "https://montblanc.utmb.world/races/TDS; UNOFFICIAL tracedetrail.fr/en/trace/183308",
    login: "No",
    terms: "Private property",
    groupLabel: "100K",
  },
  {
    id: "transgrancanaria-classic-126k-49",
    row: 49,
    name: "Transgrancanaria Classic 126K",
    organizer: "Arista Eventos",
    location: "Spain – Gran Canaria",
    continent: "Europe",
    distance: "125.1 km (GPX 129.1 km @1pt/15m)",
    officialDPlus: "6580 m (org ~7000)",
    category: "100K",
    dateLabel: "Feb",
    gpxSource: "https://transgrancanaria.net/en/classic-126km/; UNOFFICIAL tracedetrail.fr/en/trace/149184",
    login: "No",
    terms: "\"GPX most reliable format\"",
    groupLabel: "100K",
  },
  {
    id: "miut-85-50",
    row: 50,
    name: "MIUT 85",
    organizer: "Madeira Island Ultra Trail",
    location: "Portugal – Madeira",
    continent: "Europe",
    distance: "80 km",
    officialDPlus: "4800 m",
    category: "100K",
    dateLabel: "Apr",
    gpxSource: "Organiser miutmadeira.com; UNOFFICIAL tracedetrail.fr/en/trace/234645",
    login: "verify/Yes",
    terms: "Levadas",
    groupLabel: "100K",
  },
  {
    id: "ultra-trail-australia-uta100-51",
    row: 51,
    name: "Ultra-Trail Australia UTA100",
    organizer: "UTA by UTMB",
    location: "Australia – Blue Mountains",
    continent: "Oceania",
    distance: "100 km (GPX 98.6–99.4 km)",
    officialDPlus: "~4400 m",
    category: "100K",
    dateLabel: "May",
    gpxSource: "https://uta.utmb.world/runners/pre-race-info (app + course maps); UNOFFICIAL tracedetrail.fr/en/trace/228879",
    login: "No",
    terms: "Blue Mtns NP",
    groupLabel: "100K",
  },
  {
    id: "hong-kong-100-hk100-52",
    row: 52,
    name: "Hong Kong 100 (HK100)",
    organizer: "Hong Kong 100 Ultra Ltd",
    location: "Hong Kong – New Territories",
    continent: "Asia",
    distance: "101.77 km",
    officialDPlus: "~5000 m",
    category: "100K",
    dateLabel: "Sat 23 Jan 2027",
    gpxSource: "Organiser hk100ultra.com/hk100; official GPX via COROS HK store (free, checkout)",
    login: "COROS: cart checkout",
    terms: "\"do our best but not always 100% accurate\"",
    groupLabel: "100K",
  },
  {
    id: "ultra-trail-cape-town-100k-53",
    row: 53,
    name: "Ultra-Trail Cape Town 100K",
    organizer: "UTCT by UTMB",
    location: "South Africa – Cape Town",
    continent: "Africa",
    distance: "~100 km",
    officialDPlus: "4400 m",
    category: "100K",
    dateLabel: "Nov (20–22 Nov 2026)",
    gpxSource: "https://www.ultratrailcapetown.com/ (route pages; GPX button not confirmed)",
    login: "verify",
    terms: "Table Mountain NP",
    groupLabel: "100K",
  },
  {
    id: "ultra-pirineu-100k-54",
    row: 54,
    name: "Ultra Pirineu 100K",
    organizer: "Ultra Pirineu (Salomon)",
    location: "Spain – Bagà, Cadí",
    continent: "Europe",
    distance: "100 km",
    officialDPlus: "6600 m",
    category: "100K",
    dateLabel: "late Sep/Oct",
    gpxSource: "https://ultrapirineu.com/en/races/ultra/ (GPX not confirmed); UNOFFICIAL Wikiloc",
    login: "verify",
    terms: "Parc Natural Cadí-Moixeró",
    groupLabel: "100K",
  },
  {
    id: "grand-raid-des-pyrenees-tour-des-lacs-55",
    row: 55,
    name: "Grand Raid des Pyrénées – Tour des Lacs",
    organizer: "GRP",
    location: "France – Hautes-Pyrénées",
    continent: "Europe",
    distance: "62–82 km",
    officialDPlus: "~4500 m",
    category: "100K",
    dateLabel: "Aug",
    gpxSource: "https://www.grandraidpyrenees.com/en/coursesgrp/ (emailed); UNOFFICIAL tracedetrail.fr",
    login: "verify",
    terms: "—",
    groupLabel: "100K",
  },
  {
    id: "eiger-e101-56",
    row: 56,
    name: "Eiger E101",
    organizer: "Eiger Ultra Trail by UTMB",
    location: "Switzerland – Grindelwald",
    continent: "Europe",
    distance: "101.6 km",
    officialDPlus: "6700 m",
    category: "100K",
    dateLabel: "Jul (18 Jul 2026)",
    gpxSource: "https://eiger.utmb.world/races (E101 page)",
    login: "No",
    terms: "Alpine",
    groupLabel: "100K",
  },
  {
    id: "uts-100k-57",
    row: 57,
    name: "UTS 100K",
    organizer: "Ultra-Trail Snowdonia by UTMB",
    location: "Wales – Snowdonia",
    continent: "Europe",
    distance: "106 km",
    officialDPlus: "5400 m",
    category: "100K",
    dateLabel: "May",
    gpxSource: "https://snowdonia.utmb.world/races",
    login: "No",
    terms: "National park",
    groupLabel: "100K",
  },
  {
    id: "ultra-trail-haute-ardenne-100k-58",
    row: 58,
    name: "Ultra Trail Haute Ardenne 100K",
    organizer: "UTHA",
    location: "Belgium – Waimes/Vielsalm",
    continent: "Europe",
    distance: "100.77 km",
    officialDPlus: "2859 m",
    category: "100K",
    dateLabel: "31 Jul–2 Aug 2026",
    gpxSource: "Organiser utha.be; official traces UNOFFICIAL host tracedetrail.fr/fr/trace/299715",
    login: "Yes (TdT)",
    terms: "ITRA-certified",
    groupLabel: "100K",
  },
  {
    id: "trail-des-fantomes-100k-59",
    row: 59,
    name: "Trail des Fantômes 100K",
    organizer: "Runners' Lab Trailrunseries",
    location: "Belgium – La Roche-en-Ardenne",
    continent: "Europe",
    distance: "100 km",
    officialDPlus: "4240 m",
    category: "100K",
    dateLabel: "8–9 Aug 2026",
    gpxSource: "Organiser trailrun.be; UNOFFICIAL betrail.run gpx-path",
    login: "Yes (betrail)",
    terms: "Parcours published last-minute",
    groupLabel: "100K",
  },
  {
    id: "grizzly-100-60",
    row: 60,
    name: "Grizzly 100",
    organizer: "Bearsports",
    location: "Belgium – Voeren",
    continent: "Europe",
    distance: "100 km (also 85)",
    officialDPlus: "~2500 m",
    category: "100K",
    dateLabel: "24 Oct 2026",
    gpxSource: "bearsports.nl/bear-trail (GPX posted days before); UNOFFICIAL tracedetrail.fr/en/map/343",
    login: "—",
    terms: "\"GPX posted a few days before event\"",
    groupLabel: "100K",
  },
  {
    id: "legends-trail-lt-winter-61",
    row: 61,
    name: "Legends Trail LT (winter)",
    organizer: "Legends Trails",
    location: "Belgium – Bernardfagne (Ferrières)",
    continent: "Europe",
    distance: "~250–350 km",
    officialDPlus: "~13500 m",
    category: "multi",
    dateLabel: "19 Feb 2026",
    gpxSource: "Route via sqmtime.com/en-legendstrail (unique link)",
    login: "Participant link",
    terms: "Unsupported; self-sufficient",
    groupLabel: "100K",
  },
  {
    id: "ultra-trail-drenthe-62",
    row: 62,
    name: "Ultra Trail Drenthe",
    organizer: "Drentse Trail organizer",
    location: "Netherlands – Drenthe",
    continent: "Europe",
    distance: "~100/60 km",
    officialDPlus: "low",
    category: "100K",
    dateLabel: "Mar/Apr",
    gpxSource: "Not found (official direct); UNOFFICIAL betrail.run",
    login: "verify",
    terms: "Heathland",
    groupLabel: "100K",
  },
  {
    id: "ultra-trail-harricana-125-63",
    row: 63,
    name: "Ultra-Trail Harricana 125",
    organizer: "UTHC / Groupe Le Coureur Nordique",
    location: "Canada – Charlevoix, Quebec",
    continent: "N. America",
    distance: "124 km",
    officialDPlus: "~4000 m",
    category: "100K/100M",
    dateLabel: "11–13 Sep 2026",
    gpxSource: "https://ultratrailharricana.com/en/epreuve/uthc-125/ (GPX not confirmed)",
    login: "verify",
    terms: "Parc Hautes-Gorges; UNESCO biosphere",
    groupLabel: "100K",
  },
  {
    id: "canyons-100k-64",
    row: 64,
    name: "Canyons 100K",
    organizer: "Canyons Endurance Runs by UTMB",
    location: "USA – California",
    continent: "N. America",
    distance: "100 km",
    officialDPlus: "~4000 m",
    category: "100K",
    dateLabel: "Apr",
    gpxSource: "https://canyons.utmb.world/races/100K",
    login: "No",
    terms: "Western States Trail",
    groupLabel: "100K",
  },
  {
    id: "javelina-jundred-100k-65",
    row: 65,
    name: "Javelina Jundred 100K",
    organizer: "Aravaipa Running",
    location: "USA – Arizona",
    continent: "N. America",
    distance: "100 km",
    officialDPlus: "~1500 m",
    category: "100K",
    dateLabel: "Oct/Nov",
    gpxSource: "Organiser aravaiparunning.com/javelina (verify)",
    login: "verify",
    terms: "McDowell Sonoran",
    groupLabel: "100K",
  },
  {
    id: "ultra-trail-mt-fuji-kai69-66",
    row: 66,
    name: "Ultra-Trail Mt Fuji KAI69",
    organizer: "Mt Fuji 100 (UTMF)",
    location: "Japan – Yamanashi/Shizuoka",
    continent: "Asia",
    distance: "69 km",
    officialDPlus: "~2900 m",
    category: "100K",
    dateLabel: "Apr/May",
    gpxSource: "https://www.ultratrailmtfuji.com/en/racers/course/",
    login: "No",
    terms: "Permit-only sections; test courses separate",
    groupLabel: "100K",
  },
  {
    id: "tarawera-100k-67",
    row: 67,
    name: "Tarawera 100K",
    organizer: "Tarawera Ultra by UTMB",
    location: "New Zealand – Rotorua",
    continent: "Oceania",
    distance: "100 km",
    officialDPlus: "~2500 m",
    category: "100K",
    dateLabel: "14 Feb 2026",
    gpxSource: "https://tarawera.utmb.world/races; UNOFFICIAL tracedetrail.fr",
    login: "No",
    terms: "Tarawera forest access restricted pre-Feb",
    groupLabel: "100K",
  },
  {
    id: "istria-100-100k-68",
    row: 68,
    name: "Istria 100 – 100K",
    organizer: "Istria 100 by UTMB",
    location: "Croatia – Istria",
    continent: "Europe",
    distance: "~110 km",
    officialDPlus: "~4600 m",
    category: "100K",
    dateLabel: "Apr",
    gpxSource: "https://istria.utmb.world/races-runners/runners/gpx-tracks",
    login: "No",
    terms: "UTMB terms",
    groupLabel: "100K",
  },
  {
    id: "julian-alps-80k-69",
    row: 69,
    name: "Julian Alps 80K",
    organizer: "Julian Alps Trail Run by UTMB",
    location: "Slovenia – Bled",
    continent: "Europe",
    distance: "80 km",
    officialDPlus: "3826 m",
    category: "100K",
    dateLabel: "17–20 Sep 2026",
    gpxSource: "https://julianalps.utmb.world/races (Routes tab)",
    login: "No",
    terms: "Follow marked paths; pasture gates",
    groupLabel: "100K",
  },
  {
    id: "nice-cote-d-azur-100k-70",
    row: 70,
    name: "Nice Côte d'Azur 100K",
    organizer: "Nice by UTMB",
    location: "France – Alpes-Maritimes",
    continent: "Europe",
    distance: "~100 km",
    officialDPlus: "~5500 m",
    category: "100K",
    dateLabel: "Sep",
    gpxSource: "https://nice.utmb.world/races (verify)",
    login: "No",
    terms: "UTMB terms",
    groupLabel: "100K",
  },
  {
    id: "val-d-aran-cdh-100k-71",
    row: 71,
    name: "Val d'Aran CDH 100K",
    organizer: "HOKA Val d'Aran by UTMB",
    location: "Spain – Val d'Aran",
    continent: "Europe",
    distance: "~105 km",
    officialDPlus: "~6500 m",
    category: "100K",
    dateLabel: "Jul",
    gpxSource: "https://valdaran.utmb.world/race/tracks",
    login: "No",
    terms: "Private property; alt tracks at /race/tracksALT",
    groupLabel: "100K",
  },
  {
    id: "kullamannen-100-72",
    row: 72,
    name: "Kullamannen 100",
    organizer: "Kullamannen by UTMB",
    location: "Sweden – Skåne",
    continent: "Europe",
    distance: "~100 km",
    officialDPlus: "~2200 m",
    category: "100K",
    dateLabel: "Oct/Nov",
    gpxSource: "https://kullamannen.utmb.world/race/tracks (verify)",
    login: "No",
    terms: "UTMB terms",
    groupLabel: "100K",
  },
  {
    id: "ultra-trail-veluwe-veluwezoom-73",
    row: 73,
    name: "Ultra Trail Veluwe/Veluwezoom",
    organizer: "organizer",
    location: "Netherlands – Gelderland",
    continent: "Europe",
    distance: "~60–100 km",
    officialDPlus: "modest",
    category: "100K",
    dateLabel: "varies",
    gpxSource: "Not found (official direct); UNOFFICIAL betrail.run",
    login: "verify",
    terms: "National park",
    groupLabel: "100K",
  },
  {
    id: "trail-verbier-x-traversee-74",
    row: 74,
    name: "Trail Verbier X-Traversée",
    organizer: "Trail Verbier St-Bernard by UTMB",
    location: "Switzerland – Val Ferret",
    continent: "Europe",
    distance: "77 km",
    officialDPlus: "5000 m",
    category: "100K",
    dateLabel: "Jul",
    gpxSource: "https://verbier.utmb.world/races",
    login: "No",
    terms: "UTMB terms",
    groupLabel: "100K",
  },
  {
    id: "chianti-ultra-trail-100k-75",
    row: 75,
    name: "Chianti Ultra Trail 100K",
    organizer: "Chianti Ultra Trail by UTMB",
    location: "Italy – Tuscany",
    continent: "Europe",
    distance: "~100 km",
    officialDPlus: "~3500 m",
    category: "100K",
    dateLabel: "Mar/Apr",
    gpxSource: "https://chianti.utmb.world/race/tracks (verify)",
    login: "No",
    terms: "UTMB terms",
    groupLabel: "100K",
  },
  {
    id: "utmb-ultra-trail-du-mont-blanc-76",
    row: 76,
    name: "UTMB (Ultra-Trail du Mont-Blanc)",
    organizer: "UTMB World Series Finals",
    location: "France/Italy/Switz – Chamonix",
    continent: "Europe",
    distance: "174 km (start Chamonix Fri 17:45; 2026 Chamonix–Les Houches section reworked after rockfalls)",
    officialDPlus: "~9900 m (2025)",
    category: "100M",
    dateLabel: "Aug",
    gpxSource: "https://montblanc.utmb.world/races/UTMB",
    login: "No",
    terms: "Private property; passage limits",
    groupLabel: "100M / Multi-stage",
  },
  {
    id: "ptl-petite-trotte-a-leon-77",
    row: 77,
    name: "PTL (Petite Trotte à Léon)",
    organizer: "UTMB World Series (team)",
    location: "France/It/Sw – Chamonix",
    continent: "Europe",
    distance: "~300 km",
    officialDPlus: "~25000 m",
    category: "multi/team",
    dateLabel: "Aug",
    gpxSource: "https://montblanc.utmb.world/races (PTL); UNOFFICIAL tracedetrail.fr/en/trace/254625",
    login: "No",
    terms: "Unmarked; navigation required",
    groupLabel: "100M / Multi-stage",
  },
  {
    id: "western-states-100-78",
    row: 78,
    name: "Western States 100",
    organizer: "WSER Foundation",
    location: "USA – California (Olympic Valley→Auburn)",
    continent: "N. America",
    distance: "100.2 mi/161 km",
    officialDPlus: "5,500 m gain (18,090 ft) / 7,000 m descent (22,970 ft), net −1,500 m",
    category: "100M",
    dateLabel: "Sat 27 Jun 2026",
    gpxSource: "https://www.wser.org/gps-info/ (right-click save; incl. aid stations)",
    login: "No",
    terms: "\"Western States is a registered trademark © WSER Foundation\"",
    groupLabel: "100M / Multi-stage",
  },
  {
    id: "hardrock-100-79",
    row: 79,
    name: "Hardrock 100",
    organizer: "Hardrock Hundred Endurance Run",
    location: "USA – Colorado (San Juans)",
    continent: "N. America",
    distance: "101.8 mi/165 km",
    officialDPlus: "33,441 ft gain + 33,441 ft descent (66,882 ft total); 2025 CCW manual lists 33,197 ft — clockwise/CCW year difference",
    category: "100M",
    dateLabel: "Jul",
    gpxSource: "https://hardrock100.com/hardrock-course.php (\"Download GPX\"); UNOFFICIAL tracedetrail.fr/en/trace/224550",
    login: "No",
    terms: "\"Not a navigation tool\"; crosses private mining land",
    groupLabel: "100M / Multi-stage",
  },
  {
    id: "leadville-trail-100-run-80",
    row: 80,
    name: "Leadville Trail 100 Run",
    organizer: "Life Time / Leadville Race Series",
    location: "USA – Colorado",
    continent: "N. America",
    distance: "100 mi/161 km",
    officialDPlus: "~4800 m (15600 ft)",
    category: "100M",
    dateLabel: "Aug",
    gpxSource: "Organiser leadvilleraceseries.com (course PDF); UNOFFICIAL goandrace.com GPX",
    login: "verify",
    terms: "Trademark; course maps PDF",
    groupLabel: "100M / Multi-stage",
  },
  {
    id: "diagonale-des-fous-81",
    row: 81,
    name: "Diagonale des Fous",
    organizer: "Grand Raid de La Réunion",
    location: "France – La Réunion",
    continent: "Africa",
    distance: "~165–180 km (year-variable)",
    officialDPlus: "~10000–10200 m",
    category: "100M",
    dateLabel: "15–18 Oct 2026",
    gpxSource: "Organiser grandraid-reunion.com; official trace UNOFFICIAL host tracedetrail.fr/fr/trace/308026",
    login: "Yes (TdT)",
    terms: "Parc National de La Réunion UNESCO",
    groupLabel: "100M / Multi-stage",
  },
  {
    id: "tor-des-geants-tor330-82",
    row: 82,
    name: "Tor des Géants (TOR330)",
    organizer: "VDA Trailers / TORX",
    location: "Italy – Aosta Valley",
    continent: "Europe",
    distance: "330 km",
    officialDPlus: "24000 m",
    category: "multi",
    dateLabel: "Sep",
    gpxSource: "https://www.torxtrail.com/it/content/downloads (official GPX, per-section)",
    login: "No",
    terms: "Marked; alt/backup tracks org-authorised only",
    groupLabel: "100M / Multi-stage",
  },
  {
    id: "tor-des-glaciers-tor450-83",
    row: 83,
    name: "Tor des Glaciers (TOR450)",
    organizer: "VDA Trailers / TORX",
    location: "Italy – Aosta Valley",
    continent: "Europe",
    distance: "450 km",
    officialDPlus: "32000 m",
    category: "multi",
    dateLabel: "Sep",
    gpxSource: "https://www.torxtrail.com/it/content/downloads (official; unmarked — GPX mandatory)",
    login: "No",
    terms: "Unmarked; download per section advised",
    groupLabel: "100M / Multi-stage",
  },
  {
    id: "tot-dret-tor130-84",
    row: 84,
    name: "Tot Dret (TOR130)",
    organizer: "TORX",
    location: "Italy – Aosta Valley",
    continent: "Europe",
    distance: "130 km",
    officialDPlus: "12000 m",
    category: "100M",
    dateLabel: "Sep",
    gpxSource: "https://www.torxtrail.com/it/content/downloads; UNOFFICIAL tracedetrail.fr/en/trace/trace/48058",
    login: "No",
    terms: "Marked",
    groupLabel: "100M / Multi-stage",
  },
  {
    id: "ultra-trail-mt-fuji-utmf-85",
    row: 85,
    name: "Ultra-Trail Mt Fuji (UTMF)",
    organizer: "Mt Fuji 100 Race Committee",
    location: "Japan – Yamanashi/Shizuoka",
    continent: "Asia",
    distance: "~165 km",
    officialDPlus: "~8000 m",
    category: "100M",
    dateLabel: "Apr/May",
    gpxSource: "https://www.ultratrailmtfuji.com/en/racers/course/ (GPX in news posts)",
    login: "No",
    terms: "Permit-only sections; test courses published separately",
    groupLabel: "100M / Multi-stage",
  },
  {
    id: "tarawera-100-miler-86",
    row: 86,
    name: "Tarawera 100 Miler",
    organizer: "Tarawera Ultra by UTMB",
    location: "New Zealand – Rotorua",
    continent: "Oceania",
    distance: "161.9 km",
    officialDPlus: "~4900 m",
    category: "100M",
    dateLabel: "14 Feb 2026",
    gpxSource: "https://tarawera.utmb.world/races; UNOFFICIAL tracedetrail.fr/en/trace/139435",
    login: "No",
    terms: "Forest access restricted pre-Feb",
    groupLabel: "100M / Multi-stage",
  },
  {
    id: "ultra-trail-australia-uta-miler-87",
    row: 87,
    name: "Ultra-Trail Australia UTA Miler",
    organizer: "UTA by UTMB",
    location: "Australia – Blue Mountains",
    continent: "Oceania",
    distance: "~161 km",
    officialDPlus: "~7000 m",
    category: "100M",
    dateLabel: "May",
    gpxSource: "https://uta.utmb.world/runners/pre-race-info",
    login: "No",
    terms: "Blue Mtns NP",
    groupLabel: "100M / Multi-stage",
  },
  {
    id: "miut-115-legend-88",
    row: 88,
    name: "MIUT 115 (Legend)",
    organizer: "Madeira Island Ultra Trail",
    location: "Portugal – Madeira",
    continent: "Europe",
    distance: "115 km",
    officialDPlus: "7100 m",
    category: "100M",
    dateLabel: "24–25 Apr 2027",
    gpxSource: "Organiser miutmadeira.com; UNOFFICIAL tracedetrail.fr/en/trace/234644",
    login: "verify/Yes",
    terms: "Coast-to-coast",
    groupLabel: "100M / Multi-stage",
  },
  {
    id: "grand-raid-des-pyrenees-ultra-tour-89",
    row: 89,
    name: "Grand Raid des Pyrénées – Ultra Tour",
    organizer: "GRP",
    location: "France – Hautes-Pyrénées",
    continent: "Europe",
    distance: "160–165 km",
    officialDPlus: "10000–10380 m",
    category: "100M",
    dateLabel: "Aug",
    gpxSource: "https://www.grandraidpyrenees.com/en/coursesgrp/ (emailed); UNOFFICIAL tracedetrail.fr event page",
    login: "verify",
    terms: "Col de Portet closures",
    groupLabel: "100M / Multi-stage",
  },
  {
    id: "trail-100-andorra-100-miles-90",
    row: 90,
    name: "Trail 100 Andorra 100 Miles",
    organizer: "Trail 100 Andorra by UTMB",
    location: "Andorra",
    continent: "Europe",
    distance: "~170 km",
    officialDPlus: "~10000 m",
    category: "100M",
    dateLabel: "Jul",
    gpxSource: "https://andorra.utmb.world/races (verify)",
    login: "No",
    terms: "UTMB terms",
    groupLabel: "100M / Multi-stage",
  },
  {
    id: "istria-100-100-miles-91",
    row: 91,
    name: "Istria 100 – 100 Miles",
    organizer: "Istria 100 by UTMB",
    location: "Croatia – Istria",
    continent: "Europe",
    distance: "~168 km",
    officialDPlus: "~6500 m",
    category: "100M",
    dateLabel: "Apr",
    gpxSource: "https://istria.utmb.world/races-runners/runners/gpx-tracks",
    login: "No",
    terms: "UTMB terms",
    groupLabel: "100M / Multi-stage",
  },
  {
    id: "nice-cote-d-azur-100m-92",
    row: 92,
    name: "Nice Côte d'Azur 100M",
    organizer: "Nice by UTMB",
    location: "France – Alpes-Maritimes",
    continent: "Europe",
    distance: "~170 km",
    officialDPlus: "~9000 m",
    category: "100M",
    dateLabel: "Sep",
    gpxSource: "https://nice.utmb.world/races (verify)",
    login: "No",
    terms: "UTMB terms",
    groupLabel: "100M / Multi-stage",
  },
  {
    id: "val-d-aran-vda-100m-93",
    row: 93,
    name: "Val d'Aran VDA (100M)",
    organizer: "HOKA Val d'Aran by UTMB",
    location: "Spain – Val d'Aran",
    continent: "Europe",
    distance: "~163 km",
    officialDPlus: "~10000 m",
    category: "100M",
    dateLabel: "Jul",
    gpxSource: "https://valdaran.utmb.world/race/tracks (+ /race/tracksALT alternatives)",
    login: "No",
    terms: "Private property",
    groupLabel: "100M / Multi-stage",
  },
  {
    id: "cocodona-250-94",
    row: 94,
    name: "Cocodona 250",
    organizer: "Aravaipa Running",
    location: "USA – Arizona",
    continent: "N. America",
    distance: "253.3 mi/408 km",
    officialDPlus: "38791 ft/~11800 m",
    category: "multi",
    dateLabel: "May",
    gpxSource: "Organiser aravaiparunning.com/cocodona (verify GPX)",
    login: "verify",
    terms: "Desert; heat/cold; part singletrack",
    groupLabel: "100M / Multi-stage",
  },
  {
    id: "moab-240-95",
    row: 95,
    name: "Moab 240",
    organizer: "Destination Trail",
    location: "USA – Utah",
    continent: "N. America",
    distance: "239.66 mi/386 km",
    officialDPlus: "31564 ft/~9620 m",
    category: "multi",
    dateLabel: "Oct",
    gpxSource: "Organiser destinationtrailrun.com/moab (verify GPX)",
    login: "verify",
    terms: "\"Inherently dangerous\"; cliffs/wildlife",
    groupLabel: "100M / Multi-stage",
  },
  {
    id: "bigfoot-200-96",
    row: 96,
    name: "Bigfoot 200",
    organizer: "Destination Trail",
    location: "USA – Washington",
    continent: "N. America",
    distance: "~206 mi/332 km",
    officialDPlus: "~42000 ft",
    category: "multi",
    dateLabel: "Aug",
    gpxSource: "Organiser destinationtrailrun.com (verify)",
    login: "verify",
    terms: "Remote; Mt St Helens",
    groupLabel: "100M / Multi-stage",
  },
  {
    id: "barkley-marathons-97",
    row: 97,
    name: "Barkley Marathons",
    organizer: "Lazarus Lake",
    location: "USA – Tennessee (Frozen Head)",
    continent: "N. America",
    distance: "~100–130 mi (unofficial)",
    officialDPlus: "~60000 ft (unofficial)",
    category: "multi",
    dateLabel: "Mar",
    gpxSource: "NO PUBLIC GPX (by design — no course map/GPX released)",
    login: "N/A",
    terms: "Secret; no official course file",
    groupLabel: "100M / Multi-stage",
  },
  {
    id: "marathon-des-sables-98",
    row: 98,
    name: "Marathon des Sables",
    organizer: "WAA / \"What An Adventure\"",
    location: "Morocco – Sahara",
    continent: "Africa",
    distance: "~250 km/6 stages (2026 ~270 km w/ 100 km queen stage)",
    officialDPlus: "desert (low D+)",
    category: "multi-stage",
    dateLabel: "5–11 Apr 2026",
    gpxSource: "NO PUBLIC GPX (roadbook only, given at bivouac); UNOFFICIAL approx. betrail.run",
    login: "N/A",
    terms: "Route deliberately secret until roadbook (Walkingwiththewounded)",
    groupLabel: "100M / Multi-stage",
  },
  {
    id: "the-montane-spine-race-99",
    row: 99,
    name: "The Montane Spine Race",
    organizer: "Montane / Spine Race Ltd",
    location: "UK – Pennine Way",
    continent: "Europe",
    distance: "268 mi/431 km",
    officialDPlus: ">10000 m",
    category: "multi",
    dateLabel: "10–13 Jan 2026",
    gpxSource: "https://www.thespinerace.com/spine-races-route-info/ (via Outdooractive)",
    login: "Outdooractive free account",
    terms: "GPX routed around private farms — follow exactly",
    groupLabel: "100M / Multi-stage",
  },
  {
    id: "dragon-s-back-race-100",
    row: 100,
    name: "Dragon's Back Race",
    organizer: "Ourea Events",
    location: "Wales – full spine",
    continent: "Europe",
    distance: "~383 km/6 days",
    officialDPlus: "~17000 m",
    category: "multi",
    dateLabel: "from 14 Sep 2026",
    gpxSource: "https://www.dragonsbackrace.com/the-route-collection/day-one … (participants-only full GPX)",
    login: "Participant access",
    terms: "\"Some sections private; special access arranged — do not access outside event\" (Dragonsbackrace)",
    groupLabel: "100M / Multi-stage",
  },
]

/** First https:// URL found in a gpxSource string, if any — for a clickable link. */
export function extractGpxUrl(gpxSource: string): string | null {
  const match = gpxSource.match(/https?:\/\/[^\s;()]+/)
  return match ? match[0].replace(/[),.]+$/, '') : null
}

export const FAMOUS_RACE_GROUPS = [
  '20K / Sky / VK',
  '50K',
  '100K',
  '100M / Multi-stage',
] as const

